### ISSUE TITLE
Fix `on` section in caller workflows

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/.github#14]
The `on.pull_request` and `on.push` in called workflow do not work. See https://github.com/codeigniter4/shield/pull/819
We need to move them to caller workflows.

https://github.com/codeigniter4/.github/blob/4eaabb651bf45239fad310b1e70056301371a9fe/.github/workflows/deptrac.yml#L3-L19

- [x] shield https://github.com/codeigniter4/shield/pull/827
- [x] tasks https://github.com/codeigniter4/tasks/pull/131
- [x] settings https://github.com/codeigniter4/settings/pull/95
- [x] cache https://github.com/codeigniter4/cache/pull/18

**Comment by MGatner** [comment]
That's unfortunate because it is a significant amount of duplication. It does make sense though, and prevents security issues.
